### ISSUE TITLE
Login via Nick

### ISSUE THREAD

**Issue by eurofurence** [eurofurence/Stage-Squirrel#12]
I do assume the nicks are required to be unique? if not, we should do that.

And then I'd like to request to be able to login with nick+password instead of email+password
Ideally the nick-comparison should be case-insensitive (but afterwards only use the known case from the db) and support more than just alphanumeric, e.g. dashes and spaces.

**Comment by blackfurball** [comment]
Fine by me. The initial idea to use e-mail addresses for the login was that people usually remember them the most. But since we currently do not use the e-mail address for anything else then the login and we can create new accounts at all times (And, from what I understand, that change is quickly implemented), I don't see why we shouldn't do this.

**Comment by kandril** [comment]
Solved and in pull-request. Looks like it works, but will be merged into develop later.
